# Generated by Django 4.0 on 2021-12-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_rename_path_importer_import_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importer',
            name='import_path',
            field=models.CharField(max_length=200),
        ),
    ]
