# Generated by Django 4.0 on 2021-12-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
                ('date_taken', models.DateTimeField()),
                ('camera_make', models.CharField(max_length=100)),
                ('camera_model', models.CharField(max_length=100)),
                ('lens_model', models.CharField(max_length=100)),
            ],
        ),
    ]
