# Generated by Django 4.0 on 2022-01-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='lens_model',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
