# Generated by Django 4.0 on 2022-01-02 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_image_lens_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='aperture',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='exposure_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='focal_length',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
