# Generated by Django 4.0 on 2022-01-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_aperture_image_exposure_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-filename']},
        ),
        migrations.AddField(
            model_name='image',
            name='aperture_str',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='exposure_time_str',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='focal_length_str',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
