# Generated by Django 4.0 on 2022-01-03 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_image_options_image_aperture_str_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='aperture_str',
        ),
        migrations.RemoveField(
            model_name='image',
            name='exposure_time_str',
        ),
        migrations.RemoveField(
            model_name='image',
            name='focal_length_str',
        ),
    ]
