# Generated by Django 4.0 on 2022-01-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_remove_image_aperture_str_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='camera_make',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='camera_model',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='date_taken',
            field=models.DateTimeField(null=True),
        ),
    ]
