# Generated by Django 4.0 on 2022-01-04 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_alter_image_camera_make_alter_image_camera_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_make', models.CharField(max_length=100, null=True)),
                ('camera_model', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lens_model', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='camera_make',
        ),
        migrations.RemoveField(
            model_name='image',
            name='camera_model',
        ),
        migrations.RemoveField(
            model_name='image',
            name='lens_model',
        ),
        migrations.AddField(
            model_name='image',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.camera'),
        ),
        migrations.AddField(
            model_name='image',
            name='lens',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.lens'),
        ),
    ]
