# Generated by Django 4.0 on 2022-01-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_camera_lens_remove_image_camera_make_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lens',
            name='lens_model',
            field=models.CharField(default='n/a', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='camera',
            unique_together={('camera_make', 'camera_model')},
        ),
    ]
