# Generated by Django 4.0 on 2022-01-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0004_alter_directory_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='selectable',
            field=models.BooleanField(default=False),
        ),
    ]
