# Generated by Django 4.0 on 2022-01-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0005_directory_selectable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
